openapi: 3.0.3
info:
  title: Apideck
  version: 0.0.1
servers:
  - url: "https://unify.apideck.com"
  - url: "https://api.spacexdata.com/v3"
externalDocs:
  description: Apideck Developer Docs
  url: "https://developers.apideck.com"
security:
  - apiKey: []
paths:
  /hello:
    get:
      operationId: hello
      responses:
        "200":
          description: "Say hello"
          content: {}
  /rockets:
    get:
      description: list all the rockets
      operationId: rockets
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                    country:
                      type: string
                    company:
                      type: string
                    main_image:
                      type: string
                    cost_per_launch:
                      type: object
                    curruncy:
                      type: string
        "400":
          description: Invalid ID supplied
