openapi: 3.0.3
info:
  title: This is spaceX api
  version: 1.0.0
servers:
  - url: https://api.spacexdata.com/v3
tags:
  - name: rocket
    description: Everything about spaceX rockets
paths:
  /rockets:
    get:
      description: list all the rockets
      operationId: rockets
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                    country:
                      type: string
                    Company:
                      type: string
                    main_image:
                      type: string
                    cost_per_launch:
                      type: object
                    curruncy:
                      type: string
        "400":
          description: Invalid ID supplied
  /rockets/{rocket_id}:
    get:
      tags:
        - rocket
      summary: Find rocket by ID
      description: Returns a single rocket
      operationId: getRocketById
      parameters:
        - name: rocket_id
          in: path
          description: ID of rocket to return
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
# components:
#   schemas:
#     Schema:
#       type: object
#       properties:
#         id:
#           type: integer
#           format: int64
