# openapi: 3.0.3
# info:
#   title: "This is spaceX api"
#   version: "1.0.2"
# servers:
#   - url: https://api.spacexdata.com/v3

# paths:
#   /rockets:
#     description: displays all the rockets
#     get:
#       operationId: rocketsOne
#       responses:
#         "200":
#           description: successful operation
# schemas:
#   Rockets:
#     type: array
#     properties:
#       id:
#         type: integer
#         format: int64
#       country:
#         type: string
#       Company:
#         type: string
#       main_image:
#         type: string
#       cost_per_launch:
#         type: integer
#         content: {}
#         "400":
#           description: Rocket not found
openapi: 3.0.3
info:
  title: This is spaceX api
  version: 1.0.0-oas3
servers:
  - url: https://api.spacexdata.com/v3
tags:
  - name: rocket
    description: Everything about spaceX rockets
paths:
  /rockets:
    get:
      tags:
        - rocket
      summary: list all the rockets
      operationId: rocketsOne
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid ID supplied
      components: null
      application/json:
        schema:

      properties:
        id:
          type: integer
        country:
          type: string
        company:
          type: string
        main_image:
          type: string
        cost_per_launch:
          type: integer
  /rockets/{rocket_id}:
    get:
      tags:
        - rocket
      summary: Find rocket by ID
      description: Returns a single rocket
      operationId: getRocketById
      parameters:
        - name: rocket_id
          in: path
          description: ID of rocket to return
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
# components:
#   schemas:
#     Schema:
#       type: object
#       properties:
#         id:
#           type: integer
#           format: int64
